import Head from 'next/head';
import "../../public/assets/css/plugins/swiper.min.css";
import "../../public/assets/css/plugins/fontawesome-5.css";
import "../../public/assets/css/plugins/animate.min.css";
import "../../public/assets/css/plugins/unicons.css";

import "../../public/assets/css/vendor/bootstrap.min.css";
import "../../public/assets/css/style.css";
import Preloader from '@/components/preloader/Preloader';

export const metadata = {
  title: "Pinnacle Inc",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/fav.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Pinnacle Inc</title>
        <meta name="author" content="Pinnacle Inc" />
        <meta name="description" content="Pinnacle Inc" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/fav.png" />
      </Head>
      <body className="index-one">
        {/* Preloader should be on top */}
        <Preloader />

        {/* Your site content */}
        {children}
      </body>
    </html>
  );
}
